grafana:
  enabled: true
  adminPassword: "Tuckerlikeslasers09!"   # Change this!
  persistence:
    enabled: true
    size: 5Gi

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false   # Important for custom selectors

    additionalScrapeConfigs: |
      - job_name: pihole
        static_configs:
          - targets: ['pihole-metrics.pihole.svc.cluster.local:9617']
        metrics_path: /metrics
        scheme: http

# Optional: Reduce resource usage for Raspberry Pi
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 500m


#- job_name: pihole-exporter
        #static_configs:
          #          - targets: ['pihole-exporter-metrics.pihole.svc.cluster.local:9617']
        #metrics_path: /metrics
        #scheme: http
        #scrape_interval: 30s
